spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 161453
    url: jdbc:mysql://localhost/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true